DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS posts;

CREATE TABLE IF NOT EXISTS users (
    user_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(50) NOT NULL,
    login    varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS subscriptions (
    user_id1     bigint  NOT NULL,
    user_id2     bigint  NOT NULL,
    CONSTRAINT fk_subscription_user_id1 FOREIGN KEY (user_id1) REFERENCES users (user_id) ON delete CASCADE,
    CONSTRAINT fk_subscription_user_id2 FOREIGN KEY (user_id2) REFERENCES users (user_id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS posts (
    post_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        varchar(500) NOT NULL,
    author_id   bigint NOT NULL
);

INSERT INTO users (name, login)
VALUES ('Tom', '1'),
       ('Ben', '2'),
       ('Mike', '3'),
       ('Rob', '4');

INSERT INTO posts (text, author_id)
VALUES ('qwe', 1),
       ('asd', 1),
       ('zxc', 3),
       ('cxz', 3);

INSERT INTO subscriptions (user_id1, user_id2)
VALUES (1, 2),
       (1, 3),
       (2, 1),
       (2, 4),
       (3, 1),
       (3, 2),
       (3, 4);