DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS posts;

CREATE TABLE IF NOT EXISTS users (
    user_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(50) NOT NULL,
    login    varchar(50) NOT NULL,
    CONSTRAINT uc_user_login UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS subscriptions (
    user_id1     bigint  NOT NULL,
    user_id2     bigint  NOT NULL,
--    CONSTRAINT pk_friendship PRIMARY KEY (user_id1, user_id2),
    CONSTRAINT fk_subscription_user_id1 FOREIGN KEY (user_id1) REFERENCES users (user_id) ON delete CASCADE,
    CONSTRAINT fk_subscription_user_id2 FOREIGN KEY (user_id2) REFERENCES users (user_id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS posts (
    post_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(500) NOT NULL,
    author_id   bigint NOT NULL
);